{{- if .Values.rancher.bootstrapPassword -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rancher.fullname" . }}-bootstrap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rancher.labels" . | nindent 4 }}
type: Opaque
stringData:
  bootstrapPassword: {{ .Values.rancher.bootstrapPassword | quote }}
{{- end }}
