apiVersion: v1
kind: Service
metadata:
  name: {{ include "rancher.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rancher.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: https
      port: {{ .Values.service.httpsPort }}
      targetPort: https
      protocol: TCP
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "rancher.selectorLabels" . | nindent 4 }}
